# config/tickers_list.yaml

# ── app settings ─────────────────────────────────────────────
start_date: "2012-01-01"
date_format: "%Y-%m-%d"
long_process_refresh_seconds: 30

# ── tickers ──────────────────────────────────────────────────
tickers:
  - AAPL
  - MSFT
  - GDX
  - IONQ
  - 7974.T
  - CGW
  - PTLC
  - HD
  - QS
  - NVDA
  - AVAV
  - SMCI
  - BB
  - FDX
  - TMC
  - PAYX
  - SRFM
  - PLTR
  - SRFM
  - ULY
  - PSTV
  - CRWD
  - GIS
  - NVO
  - GCTK
  - SITM
  - SONM
  - CHYM
  - TIGR
  - QSI
  - ICU
  - BMBL
  - MONC.VI
  - HD
